int_Setting_Hotkey_Bike = 1
int_Setting_Hotkey_OldRod = 2
int_Setting_Hotkey_GoodRod = 3
int_Setting_Hotkey_SuperRod = 4
int_Setting_Hotkey_ItemFinder = 0
int_Setting_HotkeyFM_SweetScent = 7
int_Setting_HotkeyFM_Cut = 0
int_Setting_HotkeyFM_Fly = 0
int_Setting_HotkeyFM_Surf = 0
int_Setting_HotkeyFM_Strength = 0
int_Setting_HotkeyFM_Flash = 0
int_Setting_HotkeyFM_Dig = 8
int_Setting_HotkeyFM_Teleport = 9
int_Setting_HotkeyFM_SoftBoiled = 0
int_Setting_HotkeyFM_Whirlpool = 0
int_Setting_HotkeyFM_Waterfall = 0
int_Setting_HotkeyFM_RockSmash = 0
int_Setting_HotkeyFM_Headbutt = 0
int_Setting_HotkeyFM_MilkDrink = 0
int_Setting_HotkeyFM_Dive = 0
int_Setting_HotkeyFM_SecretPower = 0
int_Setting_HotkeyFM_Defog = 0
int_Setting_HotkeyFM_RockClimb = 0
int_Setting_HotkeyFM_Chatter = 0
int_Setting_WaitingTime_Min = 80
int_Setting_WaitingTime_Max = 220
int_Setting_Steps_Min = 8
int_Setting_Steps_Max = 10
int_PP_Base_SweetScent = 32
int_PP_Current_SweetScent = 32
bool_Setting_Steps_AlwaysRun = true
bool_Strategy_Catching_Sleep = true
bool_Strategy_Catching_Paralize = false
bool_Strategy_Catching_FalseSwipe = true
int_Strategy_Catching_LeftOverHP = 10
bool_Strategy_Catching_HealWhenSleepPPAreEmpty = false
bool_Strategy_Catching_HealWhenParalizePPAreEmpty = false
bool_Strategy_Catching_HealWhenFalseSwipePPAreEmpty = true
bool_Strategy_Fighting_FightAgainstHordes = true
bool_Strategy_Fighting_SaveUpMultiTargetMoves = true
bool_Strategy_Training_EVTrainHP = true
bool_Strategy_Training_EVTrainAttack = true
bool_Strategy_Training_EVTrainDevense = true
bool_Strategy_Training_EVTrainSpecialAttack = true
bool_Strategy_Training_EVTrainSpecialDevense = true
bool_Strategy_Training_EVTrainSpeed = true
array_Strategy_Training_LearnNewMoves = {"Skip","Stop bot","Replace first"}
bool_Strategy_PayDayThief_SkipResistantEnemies = true
bool_Strategy_PayDayThief_HealWhenPayDayPPAreEmpty = true
bool_Strategy_PayDayThief_HealWhenThiefPPAreEmpty = true
int_Item_Current_Pokeball = 100
int_Item_Current_Greatball = 10
int_Item_Current_Ultraball = 0
int_Item_Current_Masterball = 0
array_Activities_Basic_Mode = {"Walk routes","Playthrough","Record","Stay in area"}
array_Activities_Routes_Route = {"Hoenn route 102","Hoenn victory road","Cinnabar Island","Dragonspiral (Fishing)","Kanto route 10","Kanto route 15","Hoenn route 117","Hoenn route 113","Hoenn route 113 (Collect Ash)","Hoenn route 121"}
bool_Activities_Routes_DigAndTeleportBack = false
array_Activities_Behavior_MovementAtDestination = {"Do nothing","Move (up/down)","Move (left/right)","Sweet Scent","Walk back"}
array_Activities_Behavior_TaskInBattle = {"Farming","EXP-Training","EV-Training","Pay Day","Thief"}
array_Activities_Behavior_RodToUse = {"Old Rod","Good Rod","Super Rod"}
bool_Strategy_Catching_FightIfUnwanted = true
array_Activities_Playthrough_Chapter = {"Test Chapter 1: Just a little Dance","Test Chapter 2: Into the forest","Test Chapter 3: Around the Center","Test Chapter 4: Talk inside the other House"}
bool_Activities_Playthrough_ContinueNextChapter = true
array_Activities_Playthrough_Starter = {"Grass","Fire","Water"}
bool_Pokemon_Catch_CatchAlways = false
bool_Pokemon_Catch_OnlyKeepIfIV = false
pokemonArray_Pokemon_Catch_CatchAlways = {7,25,52,4,155,152,158,113,116,132,133,147,227,246,252,255,258,280,374,387,390,393,443,204,131,95,1,120,353,92}
pokemonArray_Pokemon_Catch_OnlyKeepIfIV = {52,113,116,132,133,147,246,280,374,443,131,95,120,353,25,92,204,227}
bool_Rec_Settings_FightAutomatically = true
int_Hidden_Setting_LastPokemonCaught = 0
bool_Hidden_Setting_Debug = false
array_Hidden_Record_LastOutput = {"0","0"}